version: '3'
services:
  app:
  #Dockerfile storage location
    build:
      context: ./
    depends_on:
      - database
    image: n-app
    #volumes setting
    volumes:
      - "./app:/src"
    #Container name
    container_name: n-app
    #Port connection
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mydatabase
    tty: true

  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: mydatabase
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
